### ISSUE TITLE
Log warnings

### ISSUE THREAD

**Issue by ehhc** [freefair/jsass-gradle-plugin#4]
Hi there, 
it would be a nice feature if there would be an option to get the warning the sass compilation has found.

Unfortunately to get these warning seems not to be possible with your plugin yet.
If I understand this (http://jsass.readthedocs.io/en/latest/functions.html#special-functions-warn-error-debug) correct, logging the warning could be achived with defining a custom @WarnFunction Function and add it to the options.getFunctionProviders()

I'm new with gradle plugins and wasn't able to figure out how to build and test your plugin locally. I hope you'll add an option to log the warnings.

Thanks for your plugin

**Comment by larsgrefer** [comment]
I will have a look

**Comment by larsgrefer** [comment]
@ehhc Try version `0.6.0`

**Comment by ehhc** [comment]
It works as intended - Thanks
